# Generated by Django 6.0 on 2025-12-23 20:17

from django.db import migrations

def create_default_preset(apps, schema_editor):
    GamePreset = apps.get_model('game', 'GamePreset')
    if not GamePreset.objects.filter(slug='').exists():
        GamePreset.objects.create(
            title='Wordle',
            description='The classic game.',
            letter_count=5,
            max_guesses=6,
            word_bank='APPLE, BEACH, BRAIN, BREAD, BRUSH, CHAIR, CHEST, CHORD, CLICK, CLOCK, CLOUD, DANCE, DIARY, DRIVE, DRONE, EVENT, FEAST, FIELD, FLUIT, FLASK, FRAME, FRUIT, GLASS, GRAPH, GREEN, GROUP, GUEST, GUIDE, HEART, HORSE, HOUSE, IMAGE, JUICE, LIGHT, LEMON, MELON, MONEY, MONTH, MOUNT, MOUSE, MOVIE, MUSIC, NIGHT, NORTH, NOVEL, NURSE, OCEAN, PARTY, PHONE, PHOTO, PIANO, PILOT, PITCH, PLANE, PLANT, PLATE, POINT, POUND, POWER, PRESS, PRICE, PRIDE, PRIZE, PROOF, QUEEN, RADIO, RANGE, RATIO, RIVER, ROBOT, ROUND, ROUTE, SCALE, SCENE, SCOPE, SCORE, SENSE, SHAPE, SHARE, SHEEP, SHEET, SHIFT, SHIRT, SHOCK, SHOOT, SHORT, SIGHT, SKILL, SLEEP, SMILE, SMOKE, SOUND, SOUTH, SPACE, SPEED, SPITE, SPORT, SQUAD, STAFF, STAGE, START, STEAM, STEEL, STOCK, STONE, STORE, STUDY, STUFF, STYLE, SUGAR, TABLE, TASTE, TERRY, THEME, THING, TITLE, TOTAL, TOUCH, TOWER, TRACK, TRADE, TRAIN, TREAT, TRUCK, TRUST, TRUTH, UNCLE, UNION, UNITY, VALUE, VIDEO, VISIT, VOICE, WASTE, WATCH, WATER, WHILE, WHITE, WHOLE, WOMAN, WORLD, WORRY, WRITE, WRONG, YEAST, YOUNG, YOUTH, ZEBRA',
            creator=None,
            slug=''
        )

def remove_default_preset(apps, schema_editor):
    GamePreset = apps.get_model('game', 'GamePreset')
    GamePreset.objects.filter(slug='').delete()

class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_preset, remove_default_preset),
    ]
